# Generated by Django 4.2.4 on 2023-08-17 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('available_time', models.FloatField()),
                ('unplanned_downtime', models.FloatField()),
                ('ideal_cycle_time', models.FloatField()),
                ('available_operating_time', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_id', models.IntegerField()),
                ('log_date', models.DateTimeField()),
                ('units_produced', models.IntegerField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oee_api.machine')),
            ],
        ),
    ]
